# Generated by Django 3.2.9 on 2021-11-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPlaylist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='playlisy_de_origem',
            new_name='playlist_de_origem',
        ),
    ]
